Remove macOS fontconfig workaround
conda-forge/sensormapgeo-feedstock pull request #13
Opened 2022-03-16 00:17 UTC by pkgw

The macOS fontconfig workaround is no longer needed, cf. https://github.com/conda-forge/fontconfig-feedstock/issues/54.

* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2022-03-16 00:17 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-03-16 11:15 UTC, danschef commented
Thanks for the PR, but the OSX build still fails for Python 3.7 with the same error:
```
import: 'sensormapgeo'
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/sensormapgeo_1647390009288/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/osgeo/__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/runner/miniforge3/conda-bld/sensormapgeo_1647390009288/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/sensormapgeo_1647390009288/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/osgeo/_gdal.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libfontconfig.1.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/sensormapgeo_1647390009288/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libpoppler.115.0.0.dylib
  Reason: Incompatible library version: libpoppler.115.dylib requires version 14.0.0 or later, but libfontconfig.1.dylib provides version 13.0.0
```

This is why I implemented the workaround. Probably a minimal version pinning is missing on the GDAL or poppler side?

2022-03-17 10:57 UTC, danschef requested changes
@pkgw: The build for OSX fails again after removing the fontconfig workaround. How can this be solved?

2022-03-17 13:54 UTC, pkgw commented
I need to sit down and figure out why the Python 3.7 build is selecting poppler 21.x rather than 22.x — which I always have a lot more trouble doing than I feel like I should. But like you said above, there must be some kind of pinning issue — some dep associated with the older 3.7 builds that isn't compatible with the newer packages.

2022-03-18 01:56 UTC, pkgw commented
Aha. OK. I don't feel too bad about taking a while to chase this down:

- On Python 3.7, the latest available version of `pyproj` is 3.2.1 — the 3.3.x series requires Python 3.8 or newer
- Which requires `proj` 8.x
- Which forces the use of older builds of `libspatialite`
- Which forces the use of older `geos` (3.10.1)
- Which forces the use of older `gdal` (3.4.0)
- Which forces the use of older `poppler`
- Which no longer works

The "correct" solution, if you ask me, would be to create a branch for the 3.2.x series of pyproj so that new builds for Python 3.7 can keep on being created as the ecosystem pins update.

Alternatively, one could just give up on Python 3.7 for this package. I don't have the context to know how acceptable that thought is.

2022-03-18 11:12 UTC, danschef commented
Thanks a lot for looking into this. It does not really explain why the 3.7 builds for Linux and Windows are working then. Anyway, I just asked in the pyproj-feedstock if it could be an option to add Python 3.7 builds back there. I think this would be the easiest way to solve the issue. I would like to avoid dropping Python 3.7 already as there is still quite some time until it reaches its end-of-life status in June 2023. 

But is there any concern about pinning fontconfig to 2.13.1 here as a workaround for OSX? I know, it is not a clean solution as sensormapgeo does not depend on fontconfig directly. But I also have the same issue in https://github.com/conda-forge/geoarray-feedstock/pull/56 and need to find a solution.

2022-03-18 13:04 UTC, pkgw commented
@danschef So, the version number regression in fontconfig only happened with the macOS shared library, due to some funkiness with how the build system(s) and respective versioning schemes work. On Linux, the version numbers are compatible, and Windows doesn't have that kind of versioning.

If you intend to keep support Python 3.7 in this package for a while, I'd strongly suggest that we see about making a branch for pyproj. This particular issue can be worked around with a relatively simple pin, but pyproj is associated with a fairly complex dependency tree that is only going to get more and more out of date as time passes without a new build.

I'll create a trial branch and double-check that it unblocks things here. If so, I can propose a new branch in the pyproj feedstock.

2022-03-18 16:36 UTC, pkgw commented
OK, my tests worked out well, so I've created a proposal PR in pyproj, as autolinked by GitHub above.

2022-03-22 00:41 UTC, pkgw commented
Discussion in the `pyproj` PR hasn't exactly achieved a firm conclusion, but there doesn't seem to be a huge amount of interest in adding the necessary pyproj rebuild, given that 3.7 is outside of conda-forge's nominal support window. (And will only be getting moreso when Python 3.11 drops soon.)

In that context, I'd recommend one of two courses of action:

- Drop support for Python 3.7 here, or
- Pin the older fontconfig for Python 3.7 only

2022-03-22 10:07 UTC, danschef commented
Thanks @pkgw, I will pin fontconfig for OSX and Python 3.7 only and drop Python 3.7 as soon as 3.11 is out. Do you know if fontconfig 2.13.1 is the only version that works or can I allow more?

2022-03-22 12:19 UTC, danschef commented
I am closing this in favour of https://github.com/conda-forge/sensormapgeo-feedstock/pull/14.

2022-03-22 12:19 UTC, closed without merging